/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TELEMETRY_PB_H_INCLUDED
#define PB_TELEMETRY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Mensaje de telemetría del nodo ambiental */
typedef struct _EnvironmentalData {
    /* Timestamp (POSIX epoch, segundos) */
    bool     has_timestamp;
    uint32_t timestamp;
    /* BME688 */
    bool     has_temperature;
    float    temperature;
    bool     has_humidity;
    float    humidity;
    bool     has_iaq;
    float    iaq;
    bool     has_iaq_accuracy;
    uint32_t iaq_accuracy;
    /* SCD41 */
    bool     has_co2_ppm;
    uint32_t co2_ppm;
    /* BMV080 */
    bool  has_pm1_0;
    float pm1_0;
    bool  has_pm2_5;
    float pm2_5;
    bool  has_pm10_0;
    float pm10_0;
    /* Diagnóstico */
    bool     has_battery_mv;
    uint32_t battery_mv;
    bool     has_sleep_cycles;
    uint32_t sleep_cycles;
} EnvironmentalData;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define EnvironmentalData_init_default                                                                                 \
    { false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0 }
#define EnvironmentalData_init_zero                                                                                    \
    { false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0 }

/* Field tags (for use in manual encoding/decoding) */
#define EnvironmentalData_timestamp_tag 1
#define EnvironmentalData_temperature_tag 2
#define EnvironmentalData_humidity_tag 3
#define EnvironmentalData_iaq_tag 4
#define EnvironmentalData_iaq_accuracy_tag 5
#define EnvironmentalData_co2_ppm_tag 6
#define EnvironmentalData_pm1_0_tag 7
#define EnvironmentalData_pm2_5_tag 8
#define EnvironmentalData_pm10_0_tag 9
#define EnvironmentalData_battery_mv_tag 10
#define EnvironmentalData_sleep_cycles_tag 11

/* Struct field encoding specification for nanopb */
#define EnvironmentalData_FIELDLIST(X, a)                                                                              \
    X(a, STATIC, OPTIONAL, UINT32, timestamp, 1)                                                                       \
    X(a, STATIC, OPTIONAL, FLOAT, temperature, 2)                                                                      \
    X(a, STATIC, OPTIONAL, FLOAT, humidity, 3)                                                                         \
    X(a, STATIC, OPTIONAL, FLOAT, iaq, 4)                                                                              \
    X(a, STATIC, OPTIONAL, UINT32, iaq_accuracy, 5)                                                                    \
    X(a, STATIC, OPTIONAL, UINT32, co2_ppm, 6)                                                                         \
    X(a, STATIC, OPTIONAL, FLOAT, pm1_0, 7)                                                                            \
    X(a, STATIC, OPTIONAL, FLOAT, pm2_5, 8)                                                                            \
    X(a, STATIC, OPTIONAL, FLOAT, pm10_0, 9)                                                                           \
    X(a, STATIC, OPTIONAL, UINT32, battery_mv, 10)                                                                     \
    X(a, STATIC, OPTIONAL, UINT32, sleep_cycles, 11)
#define EnvironmentalData_CALLBACK NULL
#define EnvironmentalData_DEFAULT NULL

extern const pb_msgdesc_t EnvironmentalData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define EnvironmentalData_fields &EnvironmentalData_msg

/* Maximum encoded size of messages (where known) */
#define EnvironmentalData_size 60
#define TELEMETRY_PB_H_MAX_SIZE EnvironmentalData_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
