/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TELEMETRY_TELEMETRY_PB_H_INCLUDED
#define PB_TELEMETRY_TELEMETRY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Subconjunto estricto del TelemetryPayload canónico del Gateway.
 Los field numbers son SAGRADOS y MUST coincidir con el Mega-Esquema.
 Los campos de identidad (3-5) y de ingestión (8) son inyectados por el Gateway. */
typedef struct _telemetry_TelemetryPayload {
    /* Versioning (el nodo los fija, el Gateway los valida) */
    bool     has_protocol_version;
    uint32_t protocol_version;
    bool     has_schema_version;
    uint32_t schema_version;
    /* Secuencia del nodo (para detección de huecos) */
    bool     has_node_sequence;
    uint32_t node_sequence;
    /* Tiempo de medición (ms desde epoch, rellenado por el nodo vía RTC) */
    bool     has_measured_at_ms;
    uint64_t measured_at_ms;
    /* === Ambiental y Calidad de Aire (BME688 / BSEC / SCD41) === */
    bool     has_temperature;
    float    temperature; /* Celsius (compensada por BSEC) */
    bool     has_humidity;
    float    humidity; /* % RH (compensada por BSEC) */
    bool     has_pressure;
    float    pressure; /* hPa (presión barométrica) */
    bool     has_gas_resistance;
    float    gas_resistance; /* Ohms (resistencia del MOX) */
    bool     has_iaq;
    float    iaq; /* Index of Air Quality (0-500) */
    bool     has_co2;
    uint32_t co2; /* ppm (SCD41 NDIR) */
    /* === Partículas (BMV080 Láser) === */
    bool  has_pm1_0;
    float pm1_0; /* ug/m3 */
    bool  has_pm2_5;
    float pm2_5; /* ug/m3 */
    bool  has_pm10_0;
    float pm10_0; /* ug/m3 */
    /* === Diagnósticos del Nodo === */
    bool     has_battery_mv;
    uint32_t battery_mv; /* Millivolts (ADC, futuro) */
    bool     has_sleep_cycles;
    uint32_t sleep_cycles; /* Hardware wake count */
} telemetry_TelemetryPayload;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define telemetry_TelemetryPayload_init_default                                                                        \
    {                                                                                                                  \
        false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0,  \
            false, 0, false, 0, false, 0, false, 0                                                                     \
    }
#define telemetry_TelemetryPayload_init_zero                                                                           \
    {                                                                                                                  \
        false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0,  \
            false, 0, false, 0, false, 0, false, 0                                                                     \
    }

/* Field tags (for use in manual encoding/decoding) */
#define telemetry_TelemetryPayload_protocol_version_tag 1
#define telemetry_TelemetryPayload_schema_version_tag 2
#define telemetry_TelemetryPayload_node_sequence_tag 6
#define telemetry_TelemetryPayload_measured_at_ms_tag 7
#define telemetry_TelemetryPayload_temperature_tag 9
#define telemetry_TelemetryPayload_humidity_tag 10
#define telemetry_TelemetryPayload_pressure_tag 11
#define telemetry_TelemetryPayload_gas_resistance_tag 12
#define telemetry_TelemetryPayload_iaq_tag 13
#define telemetry_TelemetryPayload_co2_tag 14
#define telemetry_TelemetryPayload_pm1_0_tag 15
#define telemetry_TelemetryPayload_pm2_5_tag 16
#define telemetry_TelemetryPayload_pm10_0_tag 17
#define telemetry_TelemetryPayload_battery_mv_tag 20
#define telemetry_TelemetryPayload_sleep_cycles_tag 21

/* Struct field encoding specification for nanopb */
#define telemetry_TelemetryPayload_FIELDLIST(X, a)                                                                     \
    X(a, STATIC, OPTIONAL, UINT32, protocol_version, 1)                                                                \
    X(a, STATIC, OPTIONAL, UINT32, schema_version, 2)                                                                  \
    X(a, STATIC, OPTIONAL, UINT32, node_sequence, 6)                                                                   \
    X(a, STATIC, OPTIONAL, UINT64, measured_at_ms, 7)                                                                  \
    X(a, STATIC, OPTIONAL, FLOAT, temperature, 9)                                                                      \
    X(a, STATIC, OPTIONAL, FLOAT, humidity, 10)                                                                        \
    X(a, STATIC, OPTIONAL, FLOAT, pressure, 11)                                                                        \
    X(a, STATIC, OPTIONAL, FLOAT, gas_resistance, 12)                                                                  \
    X(a, STATIC, OPTIONAL, FLOAT, iaq, 13)                                                                             \
    X(a, STATIC, OPTIONAL, UINT32, co2, 14)                                                                            \
    X(a, STATIC, OPTIONAL, FLOAT, pm1_0, 15)                                                                           \
    X(a, STATIC, OPTIONAL, FLOAT, pm2_5, 16)                                                                           \
    X(a, STATIC, OPTIONAL, FLOAT, pm10_0, 17)                                                                          \
    X(a, STATIC, OPTIONAL, UINT32, battery_mv, 20)                                                                     \
    X(a, STATIC, OPTIONAL, UINT32, sleep_cycles, 21)
#define telemetry_TelemetryPayload_CALLBACK NULL
#define telemetry_TelemetryPayload_DEFAULT NULL

extern const pb_msgdesc_t telemetry_TelemetryPayload_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define telemetry_TelemetryPayload_fields &telemetry_TelemetryPayload_msg

/* Maximum encoded size of messages (where known) */
#define TELEMETRY_TELEMETRY_PB_H_MAX_SIZE telemetry_TelemetryPayload_size
#define telemetry_TelemetryPayload_size 91

#ifdef __cplusplus
} /* extern "C" */
#endif

/* Convenience aliases (avoid telemetry_ prefix in application code) */
typedef telemetry_TelemetryPayload TelemetryPayload;
#define TelemetryPayload_init_default telemetry_TelemetryPayload_init_default
#define TelemetryPayload_init_zero telemetry_TelemetryPayload_init_zero
#define TelemetryPayload_fields telemetry_TelemetryPayload_fields
#define TelemetryPayload_size telemetry_TelemetryPayload_size

#endif
