#ifndef BLE_MANAGER_H
#define BLE_MANAGER_H

#include <stdint.h>
#include <stdbool.h>
#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

// Typedef for the callback when self-test is requested via BLE
typedef void (*ble_self_test_cb_t)(void);

// Typedef for the callback when epoch sync is requested via BLE
typedef void (*ble_epoch_sync_cb_t)(uint64_t epoch_s);

/**
 * @brief Run the BLE Provisioning loop blocking for up to timeout_sec
 *
 * @param timeout_sec Number of seconds to advertise before giving up.
 * @param self_test_cb Callback function to trigger self test.
 * @param epoch_sync_cb Callback function to trigger RTC sync.
 * @return true if provisioned successfully, false if timed out.
 */
bool run_ble_provisioning_loop_blocking(uint32_t timeout_sec, ble_self_test_cb_t self_test_cb,
                                        ble_epoch_sync_cb_t epoch_sync_cb);

/**
 * @brief Notify the BLE client about the latest self-test result
 *
 * @param error_bitmask The bitmask generated by the self-test
 */
void ble_manager_notify_self_test_result(uint32_t error_bitmask);

#ifdef __cplusplus
}
#endif

#endif // BLE_MANAGER_H
