syntax = "proto3";

// Mensaje de telemetría del nodo ambiental
message EnvironmentalData {
    // Timestamp (POSIX epoch, segundos)
    optional uint32 timestamp = 1;

    // BME688
    optional float temperature = 2;
    optional float humidity = 3;
    optional float iaq = 4;
    optional uint32 iaq_accuracy = 5;

    // SCD41
    optional uint32 co2_ppm = 6;

    // BMV080
    optional float pm1_0 = 7;
    optional float pm2_5 = 8;
    optional float pm10_0 = 9;

    // Diagnóstico
    optional uint32 battery_mv = 10;
    optional uint32 sleep_cycles = 11;
}
